name: simple_note_taking_app
description: "A simple note taking app."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  http: ^1.1.2
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  fpdart: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  go_router: ^13.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  loading_indicator: ^3.1.1
  awesome_snackbar_content: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.4.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
          weight: 800

flutter_gen:
  output: lib/src/resources
  line_length: 100

  integrations:
    flutter_svg: true
    lottie: true

  assets:
    enabled: true
    outputs:
      class_name: AppAssets
      package_parameter_enabled: false
      style: dot-delimiter
    exclude:
      # - Nothing to exclude
  
  fonts:
    enabled: true
    outputs:
      class_name: AppFonts
      package_parameter_enabled: false
      style: dot-delimiter
    exclude:
      # - Nothing to exclude